version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./ops/env/api.env
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - ./ops/env/worker.env
    depends_on:
      - api
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped

  proxy:
    image: caddy:2.8
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./ops/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped

volumes:
  caddy_data: {}
  caddy_config: {}
